apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
  namespace: dozzle
spec:
  type: NodePort
  selector:
    app: dozzle
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30095
