apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: NodePort
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: 30443
  selector:
    app: portainer
