apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/<your-username>/cicd-petclinic.git'
    targetRevision: main
    path: k8s/app   # path inside repo where your k8s manifests live

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
